name: Test Schemas

on: [pull_request]

jobs:
  test-xsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Test with pytest
        run: |
          pytest tests

  flatten-xsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml
      - name: Install software
        shell: bash
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo -E apt-get install -y libxml2-utils
      - name: Flatten XSD
        run: |
          cd schemas
          python ../scripts/xsdflatten.py HPXML.xsd HPXMLCombined.xsd
      - name: Commit XSD
        run: |
          branch_name="${{ github.head_ref }}"
          git pull origin $branch_name
          git add schemas/HPXMLCombined.xsd
          git status
          if [[ $(git diff --cached --exit-code) ]]; then
            git config --global user.email "github-action@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -m "Latest HPXMLCombined.xsd"
            echo "Pushing to branch: $branch_name"
            git push -u origin $branch_name
          fi
      - name: Validate XSD
        run: |
          export XSDPATH=schemas/HPXMLCombined.xsd
          xmllint --schema $XSDPATH examples/audit.xml --noout